<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Light" Id="{be8ae8b6-ba5a-4031-acf9-6c804135e679}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Light
VAR
	Counter: int;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Counter := Counter +22;]]></ST>
    </Implementation>
    <LineIds Name="Light">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>