<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b4d50afb-1b13-4589-a18b-61a811eeb4c7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	input : BOOL;
	output : bool;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[input := output;
Light();
Lamp();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>